name: deploy

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions/docker/cli@master
        run: ./build.sh
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: banst/awscli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag
        uses: docker://appropriate/curl:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "curl -X POST -H 'Accept: application/json' -H \"Authorization: Bearer $GITHUB_TOKEN\" -d @./post_tag.json https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs"
