name: tag

# on:
#   schedule:
#     - cron: "0 */6 * * *"
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://api.github.com/repos/b4nst/docker-awscli/tags | jq '.[].name' > tag-done
       