name: tag

# on:
#   schedule:
#     - cron: "0 */6 * * *"
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract releases done
        run: curl https://api.github.com/repos/b4nst/docker-awscli/tags | jq '.[].name' > tag-done
      - name: Extract releases exisiting
        run: curl https://pypi.org/pypi/awscli/json | jq '.releases | keys[]' > aws-tags
      - name: Diff
        run: grep -Fxvf tag-done aws-tags

      # - name: Tag
      #         env:
      #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #         run: "curl -X POST -H 'Accept: application/json' -H \"Authorization: Bearer $GITHUB_TOKEN\" -d @./post_tag.json https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs"
