name: tag

# on:
#   schedule:
#     - cron: "0 */6 * * *"
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract releases done
        run: curl https://api.github.com/repos/b4nst/docker-awscli/tags | jq '.[].name' > tag-done
      - name: Extract releases exisiting
        run: curl https://pypi.org/pypi/awscli/json | jq '.releases | keys[]'
      - name: Diff
        run: grep -Fxvf done exisiting